### ISSUE TITLE
Build fails with "Use of undeclared identifier 'SKStoreReviewController'"

### ISSUE THREAD

**Issue by trinhvietvan** [Elringus/iOSReviewRequest#1]
On Xcode 7 and target iOS < 10.3 will build fail with error above.
This problem can be resolve in file **IOSReviewRequest.m** like this
```
void RequestReviewInternal()
{
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 103000
    [SKStoreReviewController requestReview];
#endif
}
```

I hope this can help someone.

**Comment by elringus** [comment]
Thank you! I've committed the fix to the master branch.
